### ISSUE TITLE
keyboard shortcuts not working

### ISSUE THREAD

**Issue by 0xAalaoui** [bkbartk/mRemoteNG-develop#4]
Hello,

The keyboard shortcuts for Previous Tab and Next Tab doesn't work

**Comment by nutcr4cker** [comment]
I have the same issue. I note also you can change tabs by arrows keys <- -> if you previously click on other tab, but the problem is you will lost control to typing in console, and need to click on console witch is another issue i think.

**Comment by dcpc007** [comment]
Same as nutcr4cker, having to click inside the console after each alt-tab is very boring

**Comment by bkbartk** [comment]
hi guys,
while using SSH you can use ctrl+ tab and ctrl+ shift + tab,
the same way as it works in most modern webbrowsers.
for rdp connections this doesn't work as the keyboard focus is on the client rdp instead of your pc.

I fixed the issue with the new active console not being selected and it will be available in the beginning of next week.
